In [2]:
import numpy as np

a = np.random.randn(5)

print(a)

[-0.97651889  0.25186165  0.12438908 -0.15062093  0.29579116]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.97651889  0.25186165  0.12438908 -0.15062093  0.29579116]


In [6]:
print(np.dot(a, a.T))

1.14267515857


In [8]:
a = np.random.randn(5,1)
print(a)

[[ 2.35813922]
 [ 0.26159983]
 [-0.33479995]
 [ 0.03866173]
 [ 0.96981687]]


In [10]:
print(a.T)

[[ 2.35813922  0.26159983 -0.33479995  0.03866173  0.96981687]]


In [11]:
print(np.dot(a, a.T))

[[  5.56082056e+00   6.16888817e-01  -7.89504898e-01   9.11697395e-02
    2.28696319e+00]
 [  6.16888817e-01   6.84344709e-02  -8.75836107e-02   1.01139017e-02
    2.53703927e-01]
 [ -7.89504898e-01  -8.75836107e-02   1.12091009e-01  -1.29439451e-02
   -3.24694642e-01]
 [  9.11697395e-02   1.01139017e-02  -1.29439451e-02   1.49472930e-03
    3.74947970e-02]
 [  2.28696319e+00   2.53703927e-01  -3.24694642e-01   3.74947970e-02
    9.40544756e-01]]


In [20]:
assert(a.shape == (5,1))